# Generated by Django 5.0.6 on 2025-05-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
